### ISSUE TITLE
UniSan fails to zero initialize certain dangerous dynamic allocations

### ISSUE THREAD

**Issue by hal-ler** [sslab-gatech/unisan#1]
If the original allocation is dynamically sized, then UniSan only detects it as unsafe if it is used directly as argument to a sink function. The conservative code-paths (storing pointer to heap, inline assembly, etc.) do not trigger for dynamically sized allocations.

**Comment by kengiter** [comment]
Hey, 
Thanks for the report. 
I need to ask a few questions to confirm this issue.
1) are you using "malloc" for a user space program? UniSan currently supports only kernel space. And zero-initializing heap allocations in kernel space is by adding the "__GFP_ZERO" flag to kmalloc. Heap allocations by malloc in user space is not protected yet. To support this, we can insert a "memset" right after malloc in file llvm-3.7.1/llvm/lib/Transforms/Instrumentation/AllocSanitizer.cpp
2) have you called the instrumentation pass of UniSan, which is separated from the analysis pass?

-Kangjie

**Comment by hal-ler** [comment]
I found the bug by reading through the analysis code. I was following the code path leading to "InitDynamicAlloc".

**Comment by kengiter** [comment]
Oh, that's a "placeholder" function. The actual instrumentation is done in llvm-3.7.1/llvm/lib/Transforms/Instrumentation/AllocSanitizer.cpp

**Comment by hal-ler** [comment]
So you are telling me that https://github.com/sslab-gatech/unisan/blob/master/analysis/src/lib/SafeAllocation.cc#L98 does not have to execute for every unsafe allocation with a dynamic size? Because I don't see any other analysis in the code. The file linked by you only performs the instrumentation, but not the analysis.

**Comment by hal-ler** [comment]
What I am saying is that "InitDynamicAlloc" is not called for certain dynamic allocations. You can replicate it yourself by passing the pointer from a dynamic allocation into unsafe inline assembly.

**Comment by kengiter** [comment]
In the cases of, say inline assembly, function AllocState::SetSinkFlag() is called to indicate that the allocation reaches a sink (reachSink = true;). So "InitDynamicAlloc" will be triggered.

**Comment by hal-ler** [comment]
I suggest that you look at your own code more carefully. Especially https://github.com/sslab-gatech/unisan/blob/master/analysis/src/lib/SAStructs.cc#L119.

**Comment by kengiter** [comment]
good catch
