### ISSUE TITLE
Unmodelled external functions optimistically considered to never be sinks

### ISSUE THREAD

**Issue by hal-ler** [sslab-gatech/unisan#2]
Calls to unmodelled functions without bodies should be considered sinks in a conservative analysis. The current code actually implements this conservative behavior, but circumvents it with a continue statement. As such, these functions are considered always safe by the analysis.

https://github.com/sslab-gatech/unisan/blob/master/analysis/src/lib/SafeAllocation.cc#L791

**Comment by kengiter** [comment]
Fixed. Thanks!

**Comment by hal-ler** [comment]
Can you please publish new evaluation numbers after the fixes? These changes might have relavant performance impact and it is only fair to showcase the updated numbers.

**Comment by kengiter** [comment]
Sure.  I quickly tested it over the Android kernel (including more modules, compared with that in the paper). I think the additional performance impact is negligible, based on the following numbers. 
1. assuming empty functions as sinks
   
   # Number of static allocas:         17065
   
   # Number of dynamic allocas:        32
   
   # Number of unsafe allocas:         1675
   
   # Number of static mallocs:         2000
   
   # Number of dynamic mallocs:        1731
   
   # Number of unsafe mallocs:         584
2. not assuming empty function as sinks
   
   # Number of static allocas:         17065
   
   # Number of dynamic allocas:        32
   
   # Number of unsafe allocas:         1634
   
   # Number of static mallocs:         2000
   
   # Number of dynamic mallocs:        1731
   
   # Number of unsafe mallocs:         591

**Comment by hal-ler** [comment]
Thank you!
